services:

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: debopriyalahiri/coverage-dashboard:backend-latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: 5432
      PORT: 8081
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - E:/poc2_ami:/services
      - ./backend/config/services.docker.json:/app/config/services.json
  frontend:
    image: debopriyalahiri/coverage-dashboard:frontend-latest
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: